name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  lint-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build mkdocs without pushing, hence running in lint mode
      - uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        env:
          REQUIREMENTS: requirements.txt
